---
dependency:
  name: galaxy
  enabled: false

driver:
  name: podman

platforms:
  - name: instance
    image: python:3.9-slim
    pre_build_image: true
    command: sleep infinity

provisioner:
  name: ansible

verifier:
  name: ansible
